services:

  postgres:

    image: postgres:16

    container_name: recommendation_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recommendation_db

    ports:
      - "5432:5432"

  redis:

    image: redis:7

    container_name: recommendation_redis

    ports:
      - "6379:6379"

  backend:

    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: recommendation_backend

    env_file:
      - .env.docker

    depends_on:
      - postgres
      - redis

    ports:
      - "8000:8000"

    volumes:
      - .:/app

  frontend:

    build:
      context: ./frontend

    container_name: recommendation_frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules